APT::FTPArchive::Release {
    Origin "weekanya";
    Label "weekanya";
    Suite "stable";
    Version "2.1";
    Codename "ios";
    Architectures "iphoneos-arm64";
    Components "main";
    Description "weekanya iOS Repository";
};
