APT::FTPArchive::Release {
      Origin "weekanya";
      Label "weekanya";
      Suite "stable";
      Codename "ios";
      Architectures "iphoneos-arm64";
      Description "weekanya iOS Repository";
  };
